// ignore_for_file: avoid_print
// Run with: flutter test test/open_pdf_and_word_test.dart --reporter=expanded

import 'dart:io';
// dart:ui needed for Rect.
// ignore: unnecessary_import
import 'dart:ui';

import 'package:flutter_test/flutter_test.dart';
import 'package:path_provider_platform_interface/path_provider_platform_interface.dart';
import 'package:plugin_platform_interface/plugin_platform_interface.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';

import 'package:pdfist/services/conversion_service.dart';

class _FakePP extends Fake
    with MockPlatformInterfaceMixin
    implements PathProviderPlatform {
  final String basePath;
  _FakePP(this.basePath);
  @override
  Future<String?> getApplicationDocumentsPath() async => basePath;
}

void main() {
  test('Create sample PDF + convert to Word, open both on Desktop', () async {
    TestWidgetsFlutterBinding.ensureInitialized();

    final desktop = '/Users/tejastelkar/Desktop';
    final outDir = Directory('$desktop/PDFist_preview');
    await outDir.create(recursive: true);

    // Point path_provider at the preview folder.
    PathProviderPlatform.instance = _FakePP(outDir.path);
    await Directory('${outDir.path}/PDFist/Output').create(recursive: true);

    // ── Build a rich sample PDF ─────────────────────────────────────────────
    final doc = PdfDocument();
    doc.pageSettings.size = PdfPageSize.a4;
    doc.pageSettings.margins.all = 36;

    final titleFont = PdfStandardFont(PdfFontFamily.helvetica, 28,
        style: PdfFontStyle.bold);
    final h2Font = PdfStandardFont(PdfFontFamily.helvetica, 18,
        style: PdfFontStyle.bold);
    final bodyFont = PdfStandardFont(PdfFontFamily.helvetica, 12);
    final boldBody = PdfStandardFont(PdfFontFamily.helvetica, 12,
        style: PdfFontStyle.bold);
    final black = PdfSolidBrush(PdfColor(0, 0, 0));
    final grey = PdfSolidBrush(PdfColor(100, 100, 100));

    // ── Page 1 ──────────────────────────────────────────────────────────────
    final p1 = doc.pages.add();
    double y = 0;

    // Title
    p1.graphics.drawString('PDFist — Sample Document',
        titleFont, brush: black,
        bounds: Rect.fromLTWH(0, y, 520, 40));
    y += 50;

    // Subtitle
    p1.graphics.drawString('A demonstration of PDF → Word conversion quality',
        bodyFont, brush: grey,
        bounds: Rect.fromLTWH(0, y, 520, 20));
    y += 36;

    // Divider
    p1.graphics.drawLine(PdfPen(PdfColor(0, 0, 0), width: 0.5),
        Offset(0, y), Offset(520, y));
    y += 20;

    // Section 1
    p1.graphics.drawString('1. Introduction', h2Font, brush: black,
        bounds: Rect.fromLTWH(0, y, 520, 26));
    y += 34;
    p1.graphics.drawString(
        'PDFist processes PDF files entirely on-device with no cloud upload.\n'
        'Every operation — merge, split, compress, convert — runs locally.\n'
        'This document was generated by PDFist\'s syncfusion_flutter_pdf engine.',
        bodyFont, brush: black,
        bounds: Rect.fromLTWH(0, y, 520, 56));
    y += 64;

    // Section 2
    p1.graphics.drawString('2. Key Features', h2Font, brush: black,
        bounds: Rect.fromLTWH(0, y, 520, 26));
    y += 34;

    final features = [
      ('Merge & Split', 'Combine or divide PDFs with page-level precision.'),
      ('Compress', 'Reduce file size up to 80% using lossless algorithms.'),
      ('Protect', 'AES-256 password encryption for sensitive documents.'),
      ('Watermark', 'Add diagonal text watermarks across all pages.'),
      ('OCR', 'Make scanned PDFs text-searchable with Google ML Kit.'),
      ('Convert', 'Export to Word, Excel, HTML, Markdown, and images.'),
    ];

    for (final (label, desc) in features) {
      p1.graphics.drawString('• $label  ', boldBody, brush: black,
          bounds: Rect.fromLTWH(12, y, 100, 16));
      p1.graphics.drawString(desc, bodyFont, brush: black,
          bounds: Rect.fromLTWH(120, y, 400, 16));
      y += 22;
    }
    y += 12;

    // Section 3
    p1.graphics.drawString('3. Technical Stack', h2Font, brush: black,
        bounds: Rect.fromLTWH(0, y, 520, 26));
    y += 34;
    p1.graphics.drawString(
        'Built with Flutter (Dart) targeting Android API 21+. '
        'syncfusion_flutter_pdf handles all PDF operations. '
        'pdfrx renders pages to images for OCR and thumbnails. '
        'google_mlkit_text_recognition provides on-device OCR. '
        'Hive provides local history storage; Firestore syncs when enabled.',
        bodyFont, brush: black,
        bounds: Rect.fromLTWH(0, y, 520, 72));

    // ── Page 2 ──────────────────────────────────────────────────────────────
    final sec2 = doc.sections!.add();
    sec2.pageSettings.size = PdfPageSize.a4;
    sec2.pageSettings.margins.all = 36;
    final p2 = sec2.pages.add();
    y = 0;

    p2.graphics.drawString('4. Supported Operations', h2Font, brush: black,
        bounds: Rect.fromLTWH(0, y, 520, 26));
    y += 34;

    final ops = [
      ['Core',     'Merge, Split, Extract Pages, Delete Pages, Reorder, Rotate, Crop'],
      ['Security', 'Add Password, Remove Password, Add Permissions, Redact Areas'],
      ['Edit',     'Add Text, Add Image, Watermark, Stamp, Page Numbers, Header/Footer'],
      ['Convert',  'PDF→Word, PDF→Excel, PDF→HTML, PDF→Markdown, PDF→Text, PDF→Images'],
      ['OCR',      'Make Searchable, Extract Text from Scan, Make Selectable'],
      ['Sign',     'Draw Signature, Typed Signature, Fill Form Fields, Flatten'],
      ['Utilities','Duplicate, Reverse Pages, Interleave, N-Up Layout, Booklet'],
    ];

    for (final row in ops) {
      p2.graphics.drawString(row[0], boldBody, brush: black,
          bounds: Rect.fromLTWH(0, y, 90, 16));
      p2.graphics.drawString(row[1], bodyFont, brush: black,
          bounds: Rect.fromLTWH(96, y, 424, 16));
      p2.graphics.drawLine(
          PdfPen(PdfColor(220, 220, 220), width: 0.3),
          Offset(0, y + 20), Offset(520, y + 20));
      y += 26;
    }
    y += 14;

    p2.graphics.drawString('5. Notes on Conversion Quality', h2Font,
        brush: black, bounds: Rect.fromLTWH(0, y, 520, 26));
    y += 34;
    p2.graphics.drawString(
        'The Word export preserves headings (detected by font size ≥ 14pt), '
        'bold runs, and page structure. Complex layouts — multi-column, '
        'embedded images, tables drawn as graphics — are linearised to text '
        'runs because PDF has no semantic table or column model.\n\n'
        'For documents that are primarily text-based (reports, letters, '
        'contracts), output quality is high. For design-heavy PDFs, the '
        'exported Word file faithfully captures all readable text in reading '
        'order.',
        bodyFont, brush: black,
        bounds: Rect.fromLTWH(0, y, 520, 120));
    y += 130;

    p2.graphics.drawString('Generated by PDFist · All processing on-device',
        PdfStandardFont(PdfFontFamily.helvetica, 9),
        brush: grey,
        bounds: Rect.fromLTWH(0, y, 520, 14));

    // Save PDF to Desktop.
    final pdfPath = '${outDir.path}/PDFist_sample.pdf';
    File(pdfPath).writeAsBytesSync(doc.saveSync());
    doc.dispose();

    print('\n📄 PDF saved → $pdfPath');

    // ── Convert to Word ─────────────────────────────────────────────────────
    print('Converting PDF → Word…');
    final wordResult = await ConversionService.pdfToWord(pdfPath);

    expect(wordResult.success, isTrue, reason: wordResult.error);
    print('📝 Word saved → ${wordResult.outputPath}');
    print('   PDF size : ${File(pdfPath).lengthSync()} bytes');
    print('   DOCX size: ${wordResult.outputSize} bytes');
    print('   Pages    : ${wordResult.pageCount}');

    // ── Open both with macOS default apps ───────────────────────────────────
    print('\nOpening both files…');
    await Process.run('open', [pdfPath]);
    await Future.delayed(const Duration(milliseconds: 600));
    await Process.run('open', [wordResult.outputPath!]);

    print('\nBoth files opened. Check Preview (PDF) and Word/Pages (DOCX).');
    print('Files are in: ${outDir.path}');
  }, timeout: const Timeout(Duration(minutes: 2)));
}
